profile=fast

alang=ind,id,jpn,jp,ko,eng,en,enUS,en-US
audio-file-auto=fuzzy
audio-pitch-correction=yes
autocreate-playlist=filter
border=no
brightness=2.000000
contrast=1.000000
correct-downscaling=no
directory-filter-types=video,audio
directory-mode=ignore
dither=no
dscale=bilinear
gamut-mapping-mode=desaturate
hdr-compute-peak=yes
hdr-contrast-recovery=0.300000
hdr-peak-percentile=99.995000
hls-bitrate=max
hwdec=vulkan
hwdec-codecs=all
gpu-context=waylandvk
keep-open=yes
msg-color=yes
msg-module=yes
osc=no
osd-bar=no
osd-duration=2000
osd-font=Aporetic Serif
osd-font-size=30
osd-outline-size=2
profile=fast
pulse-buffer=50
save-position-on-quit=yes
scale=bilinear
secondary-sub-pos=6
slang=ind,id,eng,en
sub-ass-override=force
sub-auto=fuzzy
sub-back-color=000000
sub-border-size=2
sub-font=Aporetic Sans
sub-font-size=32
sub-shadow-offset=1
sub-use-margins=no
target-peak=300
title-bar=no
tone-mapping=st2094-40
video-sync=display-resample
vo=gpu-next
volume-max=150
ytdl-format=bestvideo[height<=?1080][vcodec!*=av01][vcodec^=avc1]+bestaudio/best

[2K rendering]
hwdec=auto-safe
profile-cond=height >= 1440  and not (audio_codec and (container_fps == nil or container_fps == 1))
profile-desc=2K rendering

[audio]
profile-cond=audio_codec and (container_fps == nil or container_fps == 1)
sub-font=Aporetic Sans

