[completion.active]
bg = "#6e6a86"
fg = "#f6c177"

[completion.border]
fg = "#c4a7e7"

[completion.inactive]
fg = "#e0def4"

[[filetype.rules]]
fg = "#9ccfd8"
mime = "image/*"

[[filetype.rules]]
fg = "#ebbcba"
mime = "video/*"

[[filetype.rules]]
fg = "#ebbcba"
mime = "audio/*"

[[filetype.rules]]
fg = "#f6c177"
mime = "application/zip"

[[filetype.rules]]
fg = "#f6c177"
mime = "application/gzip"

[[filetype.rules]]
fg = "#f6c177"
mime = "application/tar"

[[filetype.rules]]
fg = "#f6c177"
mime = "application/bzip"

[[filetype.rules]]
fg = "#f6c177"
mime = "application/bzip2"

[[filetype.rules]]
fg = "#f6c177"
mime = "application/7z-compressed"

[[filetype.rules]]
fg = "#f6c177"
mime = "application/rar"

[[filetype.rules]]
fg = "#f6c177"
mime = "application/xz"

[[filetype.rules]]
fg = "#31748f"
mime = "application/doc"

[[filetype.rules]]
fg = "#31748f"
mime = "application/pdf"

[[filetype.rules]]
fg = "#31748f"
mime = "application/rtf"

[[filetype.rules]]
fg = "#31748f"
mime = "application/vnd.*"

[[filetype.rules]]
bold = true
fg = "#c4a7e7"
mime = "inode/directory"

[[filetype.rules]]
fg = "#e0def4"
mime = "*"

[flavor]
dark = "catppuccin-mocha"
light = "catppuccin-latte"

[help.desc]
fg = "#e0def4"

[help.footer]
fg = "#e0def4"

[help.hovered]
bg = "#6e6a86"
fg = "#e0def4"

[help.on]
fg = "#f6c177"

[help.run]
fg = "#9ccfd8"

[input.border]
fg = "#c4a7e7"

[input.selected]
bg = "#6e6a86"

[input.title]
fg = "#e0def4"

[input.value]
fg = "#e0def4"

[mgr]
syntect_theme = "/nix/store/vqmzzjazlsh0saavpdf6msd103cjba1i-base16-rose-pine.tmTheme"

[mgr.border_style]
fg = "#908caa"

[mgr.count_copied]
bg = "#31748f"
fg = "#191724"

[mgr.count_cut]
bg = "#eb6f92"
fg = "#191724"

[mgr.count_selected]
bg = "#ebbcba"
fg = "#191724"

[mgr.cwd]
fg = "#9ccfd8"

[mgr.find_keyword]
bold = true
fg = "#31748f"

[mgr.find_position]
fg = "#f6c177"

[mgr.hovered]
bg = "#26233a"
bold = true

[mgr.marker_copied]
bg = "#31748f"
fg = "#31748f"

[mgr.marker_cut]
bg = "#eb6f92"
fg = "#eb6f92"

[mgr.marker_selected]
bg = "#ebbcba"
fg = "#ebbcba"

[mgr.preview_hovered]
bg = "#26233a"
bold = true

[mode.normal_alt]
bg = "#191724"
fg = "#c4a7e7"

[mode.normal_main]
bg = "#c4a7e7"
bold = true
fg = "#191724"

[mode.select_alt]
bg = "#191724"
fg = "#31748f"

[mode.select_main]
bg = "#31748f"
bold = true
fg = "#191724"

[mode.unset_alt]
bg = "#191724"
fg = "#524f67"

[mode.unset_main]
bg = "#524f67"
bold = true
fg = "#191724"

[pick.active]
fg = "#f6c177"

[pick.border]
fg = "#c4a7e7"

[pick.inactive]
fg = "#e0def4"

[status.perm_exec]
fg = "#31748f"

[status.perm_read]
fg = "#ebbcba"

[status.perm_sep]
fg = "#9ccfd8"

[status.perm_type]
fg = "#c4a7e7"

[status.perm_write]
fg = "#eb6f92"

[status.progress_error]
bg = "#191724"
fg = "#eb6f92"

[status.progress_label]
bg = "#191724"
fg = "#e0def4"

[status.progress_normal]
bg = "#191724"
fg = "#e0def4"

[tabs.active]
bg = "#c4a7e7"
bold = true
fg = "#191724"

[tabs.inactive]
bg = "#1f1d2e"
fg = "#c4a7e7"

[tasks.border]
fg = "#c4a7e7"

[tasks.hovered]
bg = "#6e6a86"
fg = "#e0def4"

[tasks.title]
fg = "#e0def4"

[which.cand]
fg = "#9ccfd8"

[which.desc]
fg = "#e0def4"

[which.mask]
bg = "#26233a"

[which.rest]
fg = "#524f67"

[which.separator_style]
fg = "#908caa"
