[confirm]
delete_offset = [0, 0, 70, 20]
delete_origin = "center"
delete_title = "Permanently delete {n} selected file{s}?"
overwrite_content = "Will overwrite the following file:"
overwrite_offset = [0, 0, 50, 15]
overwrite_origin = "center"
overwrite_title = "Overwrite file?"
quit_content = "The following task is still running, are you sure you want to quit?"
quit_offset = [0, 0, 50, 15]
quit_origin = "center"
quit_title = "Quit?"
trash_offset = [0, 0, 70, 20]
trash_origin = "center"
trash_title = "Trash {n} selected file{s}?"

[input]
cd_offset = [0, 2, 50, 3]
cd_origin = "top-center"
cd_title = "Change directory:"
create_offset = [0, 2, 50, 3]
create_origin = "top-center"
create_title = ["Create:", "Create (dir):"]
cursor_blink = false
filter_offset = [0, 2, 50, 3]
filter_origin = "top-center"
filter_title = "Filter:"
find_offset = [0, 2, 50, 3]
find_origin = "top-center"
find_title = ["Find next:", "Find previous:"]
rename_offset = [0, 1, 50, 3]
rename_origin = "hovered"
rename_title = "Rename:"
search_offset = [0, 2, 50, 3]
search_origin = "top-center"
search_title = "Search via {n}:"
shell_offset = [0, 2, 50, 3]
shell_origin = "top-center"
shell_title = ["Shell:", "Shell (block):"]

[log]
enabled = false

[mgr]
linemode = "none"
mouse_events = ["click", "scroll"]
ratio = [1, 4, 3]
scrolloff = 5
show_hidden = false
show_symlink = true
sort_by = "alphabetical"
sort_dir_first = true
sort_reverse = false
sort_sensitive = true
sort_translit = false
title_format = "Yazi: {cwd}"

[[open.rules]]
name = "*/"
use = ["edit", "open", "reveal"]

[[open.rules]]
mime = "text/*"
use = ["edit", "reveal"]

[[open.rules]]
mime = "image/*"
use = ["open", "reveal"]

[[open.rules]]
mime = "{audio,video}/*"
use = ["play", "reveal"]

[[open.rules]]
mime = "application/{,g}zip"
use = ["extract", "reveal"]

[[open.rules]]
mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}"
use = ["extract", "reveal"]

[[open.rules]]
mime = "application/{json,x-ndjson}"
use = ["edit", "reveal"]

[[open.rules]]
mime = "*/javascript"
use = ["edit", "reveal"]

[[open.rules]]
mime = "inode/x-empty"
use = ["edit", "reveal"]

[[open.rules]]
name = "*"
use = ["open", "reveal"]

[[opener.edit]]
block = true
desc = "$EDITOR"
for = "unix"
run = "micro \"$@\""

[[opener.edit]]
desc = "code"
for = "windows"
orphan = true
run = "code %*"

[[opener.edit]]
block = true
desc = "code (block)"
for = "windows"
run = "code -w %*"

[[opener.extract]]
desc = "Extract here"
for = "unix"
run = "ya pub extract --list \"$@\""

[[opener.extract]]
desc = "Extract here"
for = "windows"
run = "ya pub extract --list %*"

[[opener.open]]
desc = "Open"
for = "linux"
run = "xdg-open \"$1\""

[[opener.open]]
desc = "Open"
for = "macos"
run = "open \"$@\""

[[opener.open]]
desc = "Open"
for = "windows"
orphan = true
run = "start \"\" \"%1\""

[[opener.play]]
for = "unix"
orphan = true
run = "celluloid \"$@\""

[[opener.play]]
for = "windows"
orphan = true
run = "mpv --force-window %*"

[[opener.play]]
block = true
desc = "Show media info"
for = "unix"
run = "mediainfo \"$1\"; echo \"Press enter to exit\"; read _"

[[opener.reveal]]
desc = "Reveal"
for = "linux"
run = "xdg-open \"$(dirname \"$1\")\""

[[opener.reveal]]
desc = "Reveal"
for = "macos"
run = "open -R \"$1\""

[[opener.reveal]]
desc = "Reveal"
for = "windows"
orphan = true
run = "explorer /select,\"%1\""

[[opener.reveal]]
block = true
desc = "Show EXIF"
for = "unix"
run = "exiftool \"$1\"; echo \"Press enter to exit\"; read _"

[pick]
open_offset = [0, 1, 50, 7]
open_origin = "hovered"
open_title = "Open with:"

[[plugin.fetchers]]
id = "mime"
if = "!mime"
name = "*"
prio = "high"
run = "mime"

[[plugin.preloaders]]
mime = "image/{avif,hei?,jxl,svg+xml}"
run = "magick"

[[plugin.preloaders]]
mime = "image/*"
run = "image"

[[plugin.preloaders]]
mime = "video/*"
run = "video"

[[plugin.preloaders]]
mime = "application/pdf"
run = "pdf"

[[plugin.preloaders]]
mime = "font/*"
run = "font"

[[plugin.preloaders]]
mime = "application/vnd.ms-opentype"
run = "font"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"

[[plugin.prepend_previewers]]
name = "*.md"
run = "glow"

[[plugin.previewers]]
name = "*/"
run = "folder"
sync = true

[[plugin.previewers]]
mime = "text/*"
run = "code"

[[plugin.previewers]]
mime = "*/{xml,javascript,x-wine-extension-ini}"
run = "code"

[[plugin.previewers]]
mime = "application/{json,x-ndjson}"
run = "json"

[[plugin.previewers]]
mime = "image/{avif,hei?,jxl,svg+xml}"
run = "magick"

[[plugin.previewers]]
mime = "image/*"
run = "image"

[[plugin.previewers]]
mime = "video/*"
run = "video"

[[plugin.previewers]]
mime = "application/pdf"
run = "pdf"

[[plugin.previewers]]
mime = "application/{,g}zip"
run = "archive"

[[plugin.previewers]]
mime = "application/x-{tar,bzip*,7z-compressed,xz,rar,iso9660-image}"
run = "archive"

[[plugin.previewers]]
mime = "font/*"
run = "font"

[[plugin.previewers]]
mime = "application/vnd.ms-opentype"
run = "font"

[[plugin.previewers]]
mime = "inode/x-empty"
run = "empty"

[[plugin.previewers]]
name = "*"
run = "file"

[preview]
cache_dir = ""
image_delay = 30
image_filter = "triangle"
image_quality = 75
max_height = 900
max_width = 600
sixel_fraction = 15
tab_size = 2
ueberzug_offset = [0, 0, 0, 0]
ueberzug_scale = 1
wrap = "no"

[tasks]
bizarre_retry = 5
image_alloc = 536870912
image_bound = [0, 0]
macro_workers = 25
micro_workers = 10
suppress_preload = false

[which]
sort_by = "none"
sort_reverse = false
sort_sensitive = false
sort_translit = false
