# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["ahci" "xhci_pci" "sd_mod" "rtsx_usb_sdmmc" "i915" "usb_storage"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];
  boot.supportedFilesystems = ["ntfs" "btrfs" "extr" "vfat" "ntfs3"];

  fileSystems."/home/xaolan/Ventoy" = {
    device = "/dev/disk/by-uuid/2488765988762A06";
    fsType = "ntfs3";
    options = ["rw" "nosuid" "nodev" "relatime" "uid=1000" "gid=100"];
  };

  fileSystems."/home/xaolan/Data1" = {
    device = "/dev/disk/by-uuid/1C8A0A998A0A6F96";
    fsType = "ntfs3";
    options = ["rw" "nosuid" "nodev" "relatime" "uid=1000" "gid=100"];
  };

  fileSystems."/home/xaolan/Data2" = {
    device = "/dev/disk/by-uuid/ECAA469DAA4663E4";
    fsType = "ntfs-3g";
    options = ["rw" "nosuid" "nodev" "relatime" "uid=1000" "gid=100"];
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = true;
}
